import Vue from 'vue'
import Icon from 'vue-awesome/components/Icon.vue'
//require('vue-awesome/icons')
require('vue-awesome/icons/close')
require('vue-awesome/icons/question')
require('vue-awesome/icons/plus')
require('vue-awesome/icons/share-alt')
require('vue-awesome/icons/pencil')
require('vue-awesome/icons/undo')
require('vue-awesome/icons/bar-chart')
require('vue-awesome/icons/arrow-left')
require('vue-awesome/icons/facebook')
require('vue-awesome/icons/twitter')
require('vue-awesome/icons/weibo')
require('vue-awesome/icons/whatsapp')
require('vue-awesome/icons/envelope')
require('vue-awesome/icons/linkedin')
require('vue-awesome/icons/reddit')

Vue.component('icon', Icon)
